### ISSUE TITLE
Update default random media reader class.

### ISSUE THREAD

**Issue by titpetric** [WowzaMediaSystems/wse-plugin-pathselector#1]
```
RandomAccessReaderFactory: createRandomAccessReader :+1: 
java.lang.Class
NotFoundException:
 com.wowza.wms.plugin.collection.mediareaders.RandomAccessReaderMediaListPathSelector|at 
java.net.URLClassLoader.findClass(URLClassLoader.java:381)|at 
java.lang.ClassLoader.loadClass(ClassLoader.java:424)|at java.lang.C

lassLoader.loadClass(ClassLoader.java:357)|at java.lang.Class.forName0(Native Method)|at 
java.lang.Class.forName(Class.java:264)|
```

As I see this class is defined in the pathselector plugin and overrides runtime config. I suppose it should point to `com.wowza.wms.plugin.pathselector.RandomAccessReaderMediaListPathSelector` ?

**Comment by titpetric** [comment]
Also, it seems this class whatever it does is not compatible with MediaCache, if you're overriding `randomAccessReaderClass` (com.wowza.wms.mediacache.impl.MediaCacheRandomAccessReader).

**Comment by rogerlittin** [comment]
The class name is supposed to be the RandomAccessReaderClass that is included with this module. It was updated form the old Module Collection version and the class name value wasn't updated correctly.

I've just updated the version on github so it should now work correctly.
