### ISSUE TITLE
Is it compatible with VOD EDGE app?

### ISSUE THREAD

**Issue by SalmaTofaily** [WowzaMediaSystems/wse-plugin-pathselector#2]
Hello,

I have configured WSE, Media Cache, and path selector, but there is a problem in the location the media files with this configuration.
Does this module work with media cache and VOD EDGE apps?
I have the same config in an HTTP origin application and it all works. What do you advice?

BR

**Comment by akeller** [comment]
Hi @SalmaTofaily I realize this is over a year old now. Were you able to get clarity on this? 

I recommend using our support forums, tech support, or Slack for a faster response.

**Comment by akeller** [comment]
Closing as stale.
